// Top 100 films as rated by IMDb users. http://www.imdb.com/chart/top
const top100Films = [
	{ title: 'The Shawshank Redemption', year: 1994, genre: "comedy" },
	{ title: 'The Godfather', year: 1972, genre: "comedy" },
	{ title: 'The Godfather: Part II', year: 1974, genre: "comedy" },
	{ title: 'The Dark Knight', year: 2008, genre: "comedy" },
	{ title: '12 Angry Men', year: 1957, genre: "comedy" },
	{ title: "Schindler's List", year: 1993, genre: "comedy" },
	{ title: 'Pulp Fiction', year: 1994, genre: "comedy" },
	{
		title: 'The Lord of the Rings: The Return of the King,',
		year: 2003, genre: "comedy",
	},
	{ title: 'The Good, the Bad and the Ugly', year: 1966, genre: "comedy" },
	{ title: 'Fight Club', year: 1999, genre: "comedy" },
	{
		title: 'The Lord of the Rings: The Fellowship of the Ring',
		year: 2001, genre: "comedy"
	},
	{
		title: 'Star Wars: Episode V - The Empire Strikes Back',
		year: 1980, genre: "comedy",
	},
	{ title: 'Forrest Gump', year: 1994, genre: "comedy" },
	{ title: "One Flew Over the Cuckoo's Nest", year: 1975, genre: "comedy" },
	{ title: 'Goodfellas', year: 1990, genre: "comedy" },
	{ title: 'The Matrix', year: 1999, genre: "comedy" },
	{ title: 'Seven Samurai', year: 1954, genre: "action" },
	{ title: 'City of God', year: 2002, genre: "action" },
	{ title: 'Se7en', year: 1995, genre: "action" },
	{ title: 'The Silence of the Lambs', year: 1991, genre: "action" },
	{ title: "It's a Wonderful Life", year: 1946, genre: "action" },
	{ title: 'Life Is Beautiful', year: 1997, genre: "action" },
	{ title: 'The Usual Suspects', year: 1995, genre: "action" },
	{ title: 'Léon: The Professional', year: 1994, genre: "action" },
	{ title: 'Spirited Away', year: 2001, genre: "action" },
	{ title: 'Saving Private Ryan', year: 1998, genre: "comedy" },
	{ title: 'Once Upon a Time in the West', year: 1968, genre: "comedy" },
	{ title: 'American History X', year: 1998, genre: "comedy" },
	{ title: 'Interstellar', year: 2014, genre: "comedy" },
	{ title: 'Casablanca', year: 1942, genre: "comedy" },
	{ title: 'City Lights', year: 1931, genre: "comedy" },
	{ title: 'Psycho', year: 1960, genre: "comedy" },
	{ title: 'The Green Mile', year: 1999, genre: "comedy" },
	{ title: 'The Intouchables', year: 2011, genre: "comedy" },
	{ title: 'Modern Times', year: 1936, genre: "comedy" },
	{ title: 'Raiders of the Lost Ark', year: 1981, genre: "comedy" },
	{ title: 'Rear Window', year: 1954, genre: "horror" },
	{ title: 'The Pianist', year: 2002, genre: "horror" },
	{ title: 'The Departed', year: 2006, genre: "horror" },
	{ title: 'Terminator 2: Judgment Day', year: 1991, genre: "horror" },
	{ title: 'Back to the Future', year: 1985, genre: "horror" },
	{ title: 'Whiplash', year: 2014, genre: "horror" },
	{ title: 'Gladiator', year: 2000, genre: "horror" },
	{ title: 'Memento', year: 2000, genre: "horror" },
	{ title: 'The Prestige', year: 2006, genre: "horror" },
	{ title: 'The Lion King', year: 1994, genre: "horror" },
	{ title: 'Apocalypse Now', year: 1979, genre: "horror" },
	{ title: 'Alien', year: 1979, genre: "horror" },
	{ title: 'Sunset Boulevard', year: 1950, genre: "horror" },
	{ title: 'The Great Dictator', year: 1940, genre: "horror" },
	{ title: 'Cinema Paradiso', year: 1988, genre: "horror" },
	{ title: 'The Lives of Others', year: 2006, genre: "comedy" },
	{ title: 'Grave of the Fireflies', year: 1988, genre: "comedy" },
	{ title: 'Paths of Glory', year: 1957, genre: "comedy" },
	{ title: 'Django Unchained', year: 2012, genre: "comedy" },
	{ title: 'The Shining', year: 1980, genre: "comedy" },
	{ title: 'WALL·E', year: 2008, genre: "comedy" },
	{ title: 'American Beauty', year: 1999, genre: "comedy" },
	{ title: 'The Dark Knight Rises', year: 2012, genre: "drama" },
	{ title: 'Princess Mononoke', year: 1997, genre: "drama" },
	{ title: 'Aliens', year: 1986, genre: "drama" },
	{ title: 'Oldboy', year: 2003, genre: "drama" },
	{ title: 'Once Upon a Time in America', year: 1984, genre: "drama" },
	{ title: 'Witness for the Prosecution', year: 1957, genre: "drama" },
	{ title: 'Das Boot', year: 1981, genre: "drama" },
	{ title: 'Citizen Kane', year: 1941, genre: "drama" },
	{ title: 'North by Northwest', year: 1959, genre: "drama" },
	{ title: 'Vertigo', year: 1958, genre: "drama" },
	{ title: 'Reservoir Dogs', year: 1992, genre: "drama" },
	{ title: 'Braveheart', year: 1995, genre: "drama" },
	{ title: 'M', year: 1931, genre: "drama" },
	{ title: 'Requiem for a Dream', year: 2000, genre: "drama" },
	{ title: 'Amélie', year: 2001, genre: "drama" },
	{ title: 'A Clockwork Orange', year: 1971, genre: "drama" },
	{ title: 'Like Stars on Earth', year: 2007, genre: "drama" },
	{ title: 'Taxi Driver', year: 1976, genre: "drama" },
	{ title: 'Lawrence of Arabia', year: 1962, genre: "drama" },
	{ title: 'Double Indemnity', year: 1944, genre: "drama" },
	{ title: 'Amadeus', year: 1984, genre: "drama" },
	{ title: 'To Kill a Mockingbird', year: 1962, genre: "drama" },
	{ title: 'Toy Story 3', year: 2010, genre: "drama" },
	{ title: 'Logan', year: 2017, genre: "drama" },
	{ title: 'Full Metal Jacket', year: 1987, genre: "drama" },
	{ title: 'Dangal', year: 2016, genre: "drama" },
	{ title: 'The Sting', year: 1973, genre: "drama" },
	{ title: '2001: A Space Odyssey', year: 1968, genre: "drama" },
	{ title: "Singin' in the Rain", year: 1952, genre: "comedy" },
	{ title: 'Toy Story', year: 1995, genre: "comedy" },
	{ title: 'Bicycle Thieves', year: 1948, genre: "comedy" },
	{ title: 'The Kid', year: 1921, genre: "comedy" },
	{ title: 'Inglourious Basterds', year: 2009, genre: "comedy" },
	{ title: 'Snatch', year: 2000, genre: "comedy" },
	{ title: '3 Idiots', year: 2009, genre: "comedy" },
	{ title: 'Monty Python and the Holy Grail', year: 1975, genre: "comedy" },
];

export default top100Films;
